### PR TITLE
Fix matmul acc delay with lock

### LINKED ISSUE #15: Update to Chisel v3.5.x

### PR DESCRIPTION
**Pull request by tdb-alcorn**
This change fixes a bug where matmuls and accs would wait on each other instead of proceeding in parallel. The problem was that the control queues feeding them were implicitly linked, meaning that one could not get too far ahead of the other. We add buffers in these places to cut dependencies between buses fed by the same control inputs. In this case the buffer size was sometimes set to 2x the array size to account for the fact that accumulate operations can't begin until data has propagated through the array.

To prevent concurrency bugs from arising due to out of order execution, we also add a lock pool module that manages a set of mutexes that are shared by a number of actors. In our case, the mutexes are locks tied to memory regions (2 locks total) and the actors are the memory ports. The decoder acquires locks when it sends off memory requests, and the locks are automatically released when the appropriate condition is met - in this case when the memory request that needs to lock is actually passed into the memory module.

This change also required upgrading to Chisel 3.5.3 to get around some odd bugs that seemed to be due to the `cloneType` methods, which are no longer necessary in this version. To effect the upgrade, we had to fix some deprecation and naming issues, such as removing unnecessary parentheses from `.fire`, `.isLit`, or moving the verification statements out of the experimental package. We also had to update tests to reflect the new API of scalatest in the latest version (cosmetic differences only).

The meat of the change is in the `LockPool` module so please start there when reviewing.

Closing #52 in favour of this new PR

Closes #15

### CODE REVIEW

**Comment by petrohi** [comment]
There is Verilator compilation issue with ChiselTest 0.5.3 preventing proper testing with simulation. We reached to Chisel Gitter for help.

Instead we tested on FPGA and confirmed correctness. Also observing significant performance improvement (see line D):

  | ResNet20 CIFAR ONNX | YOLOv4 Tiny @416 ONNX | ResNet50 ImageNet ONNX
-- | -- | -- | --
A. ZCU104 baseline (ms) | 13.099 | 294.071 | 514.279
B. A and external AXI4S Width Converter instead of Transmisson | 11.168 | 262.804 | 473.956
C. B and two-cycle read/write fix | 9.661 | 214.892 | 415.953
D. C and fix for delay between ops | 7.387 | 120.748 | 256.987

File: rtl/src/main/scala/tensil/mutex/LockPool.scala [hunk 1]
```diff
@@ -0,0 +1,145 @@
...
+  }
+  def release(l: ConditionalReleaseLock[T]): Unit = {
+    l.held := false.B
+  }
+  // this covers the case where the condition happens to be observed on the same
+  // cycle the lock would have been acquired
+  val incomingObserved =
+    lockControl.valid && actor(lockControl.bits.by).fire && actor(
+      lockControl.bits.by
+    ).bits === lockControl.bits.cond
```
Comment (petrohi) [inline rtl/src/main/scala/tensil/mutex/LockPool.scala:100]: Do we have test case where incomingObserved is true?

File: rtl/src/main/scala/tensil/mutex/LockPool.scala [hunk 2]
```diff
@@ -0,0 +1,145 @@
...
+      }
+    }
+  }
+
+  // when all actors are blocked, allow the actor holding lock 0 to proceed
+  when(block.reduce((a, b) => a && b)) {
+    io.actor(lock(0.U).by).out <> actor(lock(0.U).by)
+    // signal out when deadlock happens so we know that something is wrong
+    io.deadlocked.bits := true.B
+    io.deadlocked.valid := true.B
```
Comment (petrohi) [inline rtl/src/main/scala/tensil/mutex/LockPool.scala:143]: Is this possible to create the deadlock by supplying specific sequence of instructions?

File: rtl/src/main/scala/tensil/tcu/Accumulator.scala [hunk 3]
```diff
@@ -43,14 +45,34 @@ class Accumulator[T <: Data with Num[T]](
...
 
-  val portA        = mem.io.portA
-  val portB        = mem.io.portB
-  val portAControl = portA.control
-  val portBControl = OutQueue(portB.control, 1, pipe = true, flow = true)
+  val portA = mem.io.portA
+  val portB = mem.io.portB
+  // val portAControl = OutQueue(portA.control, 1, pipe = true, flow = true)
+  // val portBControl = portB.control
+  // val portAControlOut = OutQueue(portA.control, 1, pipe = true, flow = true)
```
Comment (petrohi) [inline rtl/src/main/scala/tensil/tcu/Accumulator.scala:58]: Maybe clean the commented lines.

File: rtl/src/main/scala/tensil/tcu/SystolicArray.scala [hunk 4]
```diff
@@ -39,7 +39,8 @@ class SystolicArray[T <: Data with Num[T]](
   val arrayPropagationDelay = height + width - 1
   val array                 = Module(new InnerSystolicArray(gen, height, width))
 
-  val input   = Queue(io.input, 2)
+  // val input   = Queue(io.input, 2)
```
Comment (petrohi) [inline rtl/src/main/scala/tensil/tcu/SystolicArray.scala:42]: Maybe clean the commented lines.

File: rtl/src/main/scala/tensil/util/decoupled/VecAdder.scala [hunk 5]
```diff
@@ -14,8 +14,10 @@ class VecAdder[T <: Data with Num[T]](gen: T, size: Int) extends Module {
     val output = Decoupled(Vec(size, gen))
   })
 
-  val left  = Queue(io.left, 1, pipe = true, flow = true)
-  val right = Queue(io.right, 1, pipe = true, flow = true)
+  // val left  = Queue(io.left, 1, pipe = true, flow = true)
+  // val right = Queue(io.right, 1, pipe = true, flow = true)
```
Comment (petrohi) [inline rtl/src/main/scala/tensil/util/decoupled/VecAdder.scala:18]: Maybe clean the commented lines.

File: rtl/src/test/scala/tensil/Scratch.scala [hunk 6]
```diff
@@ -10,13 +10,549 @@ import chisel3.util.Decoupled
 import chiseltest._
 import tensil.util.decoupled.Counter
 import chisel3.util.Queue
+import chisel3.util.DecoupledIO
+import tensil.util.zero
 
-class Scratch extends Module { val io = IO(new Bundle {}) }
+class Scratch(depth: Int) extends Module {
```
Comment (petrohi) [inline rtl/src/test/scala/tensil/Scratch.scala:16]: What Scratch stands for?

File: sim/test/src/tcu/TCUSpec.scala [hunk 7]
```diff
@@ -26,6 +27,63 @@ import tensil.mem.MemKind
 class TCUSpec extends UnitSpec {
   behavior of "TCU"
 
+  it should "process matmuls and accumulates simultaneously" in {
```
Comment (petrohi) [inline sim/test/src/tcu/TCUSpec.scala:30]: Great to have this captured!

**Review by petrohi — APPROVED** [review]
LGTM!!!

(Few curious questions and tiny nitpicks.)

File: rtl/src/test/scala/tensil/Scratch.scala (hunk 6 above)
Comment (tdb-alcorn) [reply rtl/src/test/scala/tensil/Scratch.scala:16]: This class is just for prototyping and testing ideas - everything here was moved over to LockPool so these changes can be deleted.

File: rtl/src/main/scala/tensil/mutex/LockPool.scala (hunk 1 above)
Comment (tdb-alcorn) [reply rtl/src/main/scala/tensil/mutex/LockPool.scala:100]: Added a test covering this case to `LockPoolSpec`

File: rtl/src/main/scala/tensil/mutex/LockPool.scala (hunk 2 above)
Comment (tdb-alcorn) [reply rtl/src/main/scala/tensil/mutex/LockPool.scala:143]: Good question, I think it's possible but tricky to induce because we always request locks at the same time as we actually issue the memory request. Lets do a brainstorm on this out of band.
